import { NextRequest, NextResponse } from "next/server";
import { calculateDailyCalories } from "@/lib/nutrition/calculateNutrition";
import { calculateMacros } from "@/lib/nutrition/calculateMacros";
import { supabaseAdmin } from "@/lib/supabaseAdminClient";
import { getBangladeshDate } from "@/lib/dateUtils";

export async function POST(req: NextRequest) {
	try {
		const { userId } = await req.json();

		// 🛑 TESTING LOGIC: Look for tomorrow's adjusted plan to show it today
		const today = getBangladeshDate(0);
		const tomorrow = getBangladeshDate(1);

		// 1. Check if an adjusted plan for TOMORROW exists (the one generated by your Save Today button)
		const { data: adjustedLog } = await supabaseAdmin
			.from("daily_nutrition_logs")
			.select("*")
			.eq("user_id", userId)
			.eq("date", tomorrow) // 👈 We look at tomorrow's row for testing
			.maybeSingle();

		let calories: number;
		let macros: { protein_g: number; carbs_g: number; fat_g: number };

		if (adjustedLog && adjustedLog.calories_target > 0) {
			// ✅ FOUND ADJUSTMENT: Displaying tomorrow's plan as today's
			calories = adjustedLog.calories_target;
			macros = {
				protein_g: adjustedLog.protein_target,
				carbs_g: adjustedLog.carbs_target,
				fat_g: adjustedLog.fat_target,
			};
		} else {
			// 🔄 FALLBACK: Standard Calculation
			const { data: profile } = await supabaseAdmin
				.from("profiles")
				.select("*")
				.eq("id", userId)
				.single();

			if (!profile) throw new Error("Profile not found");

			calories = calculateDailyCalories({
				weightKg: Number(profile.weight_kg),
				heightCm: Number(profile.height_cm),
				age: Number(profile.age),
				gender: profile.gender,
				activityLevel: profile.activity_level,
				fitnessGoal: profile.fitness_goal,
			});

			const calcMacros = calculateMacros(
				Number(profile.weight_kg),
				calories,
				profile.fitness_goal,
			);
			macros = {
				protein_g: calcMacros.protein_g,
				carbs_g: calcMacros.carbs_g,
				fat_g: calcMacros.fat_g,
			};
		}

		return NextResponse.json({
			mealPlan: {
				calories,
				macros,
				meals: [
					{ name: "Breakfast", calories: Math.round(calories * 0.25) },
					{ name: "Lunch", calories: Math.round(calories * 0.35) },
					{ name: "Dinner", calories: Math.round(calories * 0.3) },
					{ name: "Snack", calories: Math.round(calories * 0.1) },
				],
			},
		});
	} catch (e: any) {
		return NextResponse.json({ error: e.message }, { status: 500 });
	}
}
